### ISSUE TITLE
Automatically create a domain event hierarchy

### ISSUE THREAD

**Issue by danhaywood** [vaulttec/isis-script#13]
If you look at the isis-app-todoapp or the isis-module-security addons, say, you'll see that I create a hierarchy of events... for the member, for the class, for the module.  This is so that any subscribers on these events can choose the scope/granularity.  (A subscriber at the module level could in essence veto all that module's functionality from the UI).

Perhaps the DSL could automatically generate this event hierarchy?

**Comment by tjuerge** [comment]
For generating the (abstract) class event we need a reference to the corresponding module type. This type is provided by the optional keyword `module`, e.g.
```
module AppModule

entity SomeType {
}
```
Only if this keyword is present the corresponding event hierarchy is generated.
