### ISSUE TITLE
outline view doesn't show child nodes for actions (though it does for properties)

### ISSUE THREAD

**Issue by danhaywood** [vaulttec/isis-script#16]
I added a property:

```
@Property(optionality=OPTIONAL)
property Integer count {
    choices {
        #[1,2,3]
    }
}
```

and its "choices" node appears in the outline view, but the same is not true for the children of the "updateName" action:

```
@Action(domainEvent = UpdateNameDomainEvent)
action SimpleObject updateName {
    @Parameter(maxLength = 40)
    @ParameterLayout(named = "New name")
    parameter String newName {
        default {
            ...
        }
    }
    body {
        ...
    }
    validate {
                    ...
    }
    event UpdateNameDomainEvent
}
```

see: 

![image](https://cloud.githubusercontent.com/assets/1031625/9809332/1bff17ca-585f-11e5-9f3a-857a89f8f880.png)

**Comment by tjuerge** [comment]
Now all the child nodes are (sorted by their location in the source code) shown in the outline view:

![screen shot 2015-09-13 at 00 36 48](https://cloud.githubusercontent.com/assets/2626998/9834182/f535612e-59af-11e5-8f46-c8ef0eec5546.png)

**Comment by danhaywood** [comment]
Great stuff!
