### ISSUE TITLE
Replace deprecated DomainObjectContainer in generated code

### ISSUE THREAD

**Issue by tjuerge** [vaulttec/isis-script#30]
In [Isis version 1.12.0](https://isis.apache.org/release-notes.html#1.12.0) the [DomainObjectContainer](https://isis.apache.org/guides/rgsvc.html#_rgsvc_api_DomainObjectContainer) service has been deprecated, replaced by a number of fine-grained services (such as [RepositoryService](https://isis.apache.org/guides/rgsvc.html#_rgsvc_api_RepositoryService) and [MessageService](https://isis.apache.org/guides/rgsvc.html#_rgsvc_api_MessageService)).

The corresponding migration guide can be found [here](https://isis.apache.org/migration-notes.html#domainobjectcontainer-domain-service).

**Comment by danhaywood** [comment]
Nice to see some further work being done here.
(Merry Christmas, by the way!)
