### ISSUE TITLE
Add support for mixins

### ISSUE THREAD

**Issue by danhaywood** [vaulttec/isis-script#31]
[Mixins](http://isis.apache.org/guides/rgant.html#_rgant-Mixin) were introduced in 1.10.0 (10-nov-2015), so I think that's after the time when you did most of the work on this repo.

In terms of a keyword, I was thinking that another name for them could be "behaviour" (or "behavior", I suppose, for the US).

**Comment by tjuerge** [comment]
This can be implemented in the same way as a service but with an additional one-arg constructor. For determining the constructor argument we're using the following syntax:
```
behaviour <type name> for <constructor arg type> <constructor arg name> {
```
Example:
```
@Mixin
behaviour SimpleObject_wrappedSimpleObject for SimpleObject object {
	
	inject WrapperFactory wrapperFactory

	@Action
	action SimpleObject $$ {
		body {
			wrapperFactory.wrap(object)
		}
	}
}
```
