### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by magick93** [vaulttec/isis-script#5]
I have replaced the example SimpleObject class with the example in the readme, and the code generates fine - looks good.

However, when trying to run, I get the following:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project strategybuilder-dom: Compilation failure: Compilation failure:
[ERROR] /home/anton/Documents/software/isis/dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.java:[21,36] package domainapp.dom.modules.simple does not exist
[ERROR] /home/anton/Documents/software/isis/dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.java:[22,36] package domainapp.dom.modules.simple does not exist
[ERROR] /home/anton/Documents/software/isis/dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.java:[38,17] cannot find symbol
[ERROR] symbol:   class SimpleObject
[ERROR] location: class domainapp.dom.app.homepage.HomePageViewModel
[ERROR] /home/anton/Documents/software/isis/dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.java:[46,5] cannot find symbol
[ERROR] symbol:   class SimpleObjects
[ERROR] location: class domainapp.dom.app.homepage.HomePageViewModel
[ERROR] /home/anton/Documents/software/isis/dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.java:[21,36] package domainapp.dom.modules.simple does not exist
[ERROR] /home/anton/Documents/software/isis/dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.java:[22,36] package domainapp.dom.modules.simple does not exist
[ERROR] /home/anton/Documents/software/isis/dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.java:[38,17] cannot find symbol
[ERROR] symbol:   class SimpleObject
[ERROR] location: class domainapp.dom.app.homepage.HomePageViewModel
[ERROR] /home/anton/Documents/software/isis/dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.java:[46,5] cannot find symbol
[ERROR] symbol:   class SimpleObjects
[ERROR] location: class domainapp.dom.app.homepage.HomePageViewModel
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :strategybuilder-dom
```

Do I need to add the path to the generated source in the pom? If yes, where/how should I do that? I have tried adding:

```
 <build>
     <resources>
                    <resource>
                        <directory>target/generated-sources/isis/</directory>
                    </resource>
                </resources>
```

but this did not help.

Thanks

**Comment by tjuerge** [comment]
> Do I need to add the path to the generated source in the pom?

Sure. The plan is to come up with a Isis Script Maven plugin which generates the Java code (currently the Java code is generated via Eclipse only!!!) and adds the output folder `target/generated-sources/isis/` to the Maven projects list of source folders.

> If yes, where/how should I do that?

As a workaround use the [Build Helper Maven Plugin](http://www.mojohaus.org/build-helper-maven-plugin/usage.html) to add the output folder.

**Comment by tjuerge** [comment]
Btw. the `<resources>` tag is no alternative for the (single) `<sourceDirectory>` tag :-P

**Comment by magick93** [comment]
Thanks

Do you have an example of a working pom? I've tried with the builder helper plugin, but - well I must have it mis-configured.

**Comment by tjuerge** [comment]
> Do you have an example of a working pom? I've tried with the builder helper plugin, but - well I must have it mis-configured.

Nope, without an Isis Script Maven plugin (which generates the Java code duing a Maven build - currently the Java code is generated from within Eclipse via the Isis Script Eclipse editor only!!!) a Maven project will not work. After executing "mvn clean" the generated Java code is gone.

**Comment by tjuerge** [comment]
> > Do you have an example of a working pom? I've tried with the builder helper plugin, but - well I must have it mis-configured.
> 
> Nope, without an Isis Script Maven plugin (which generates the Java code duing a Maven build - currently the Java code is generated from within Eclipse via the Isis Script Eclipse editor only!!!) a Maven project will not work.

As mentioned in #6 using the generic [xtext-maven-plugin](https://eclipse.org/Xtext/documentation/350_continuous_integration.html) should be sufficient.

Maybe you can give it a try. Don't forget to check-out the project and run `mvn install` to install the Isis Script DSL jar in your local Maven repository.

**Comment by tjuerge** [comment]
> Do you have an example of a working pom? I've tried with the builder helper plugin, but - well I must have it mis-configured.

Please have a look into the [POM of the simpleapp example](https://github.com/vaulttec/isis-script/blob/develop/isis-script-examples/simpleapp/pom.xml).
