### ISSUE TITLE
Provide example Maven project using the Isis Script DSL via xtext-maven-plugin

### ISSUE THREAD

**Issue by tjuerge** [vaulttec/isis-script#6]
We need an exampe project which shows how to use the Isis Script DSL via the [xtext-maven-plugin](https://eclipse.org/Xtext/documentation/350_continuous_integration.html).

Stefan Oheme has described all the bloody details in his blog post [Building Xtext Languages with Maven and Gradle](https://oehme.github.io/2014/08/13/building-xtext-languages-with-maven-and.html).

**Comment by magick93** [comment]
What is the repository for the plugin?

I am getting the following:

```
[ERROR] Failed to execute goal on project strategybuilder-dom: Could not resolve dependencies for project io.tradeworks:strategybuilder-dom:jar:1.0-SNAPSHOT: Could not find artifact org.vaulttec.isis.script.eclipse:org.vaulttec.isis.script:jar:1.0-SNAPSHOT in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) -> 
```

**Comment by tjuerge** [comment]
> What is the repository for the plugin?

This jar isn't available from any public Maven repository. As mentioned in the last comment to #5 you have to build it by your own by checking-out the project and run `mvn install` to install the Isis Script DSL jar in your local Maven repository.
