### ISSUE TITLE
It'd be nice if the "quick outline" pop-up (ctrl+O) would collapse the imports by default.

### ISSUE THREAD

**Issue by danhaywood** [vaulttec/isis-script#9]
instead of this:

![image](https://cloud.githubusercontent.com/assets/1031625/9727129/63680ec8-55f3-11e5-8f77-e632b4b89f8e.png)

= better would be:

![image](https://cloud.githubusercontent.com/assets/1031625/9727133/75b32176-55f3-11e5-8c2c-951658bde1ae.png)

**Comment by tjuerge** [comment]
We should do here the same as JDTs quick outline does - remove the whole import section:

![screen shot 2015-09-13 at 17 03 59](https://cloud.githubusercontent.com/assets/2626998/9837259/9ebc3932-5a39-11e5-9190-53b65d5fc112.png)
